### ISSUE TITLE
PddlBaseListener missing

### ISSUE THREAD

**Issue by probablybayes** [hfoffani/pddl-lib#3] opened 2016-08-22 19:33 UTC
I am trying to compile the C# code as a library and it is complaining about PddlBaseListener missing. Is it a part of different package or was the code not pushed to git.

Thank you.

**Comment by hfoffani** [comment] 2016-08-23 13:07
Would you mind to post the error output? What environment are you working in?

I've just cloned a new repository and, besides copying the file Antlr4.Runtime.dll to the pddlnet directory, the library for .net compiles.

**Comment by marijngoedegebure** [comment] 2016-10-03 11:16
Hello,

I am having the same issue. First I tried installing it through nuget but that threw the following error:

"Unable to resolve dependency 'pddlnet'. Source(s) used: 'nuget.org', 'Package source', 'Microsoft Visual Studio Offline Packages'."

Looking at the nuget page of pddlnet it gives a 404 (https://www.nuget.org/packages/pddlnet/).

After that I tried your suggestion and cloned the newest version, copyied Antlr4.Runtime.dll to the pddlnet directory and use the following command to compile to a library:

C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe /target:library /out:pddlnet.dll *.cs

This resulted in the following errors, http://pastebin.com/hGYshN02 (which includes the PddlBaseListener missing, among others)

Your help is greatly appreciated.

**Comment by hfoffani** [comment] 2016-10-03 11:30
Hi,

You'll need to add the reference to Antler: `/reference:Antlr4.Runtime.dll` So your command would look like:

`C:\Windows\...\csc.exe /target:library /out:pddlnet.dll /reference:Antlr4.Runtime.dll *.cs`

**Comment by marijngoedegebure** [comment] 2016-10-03 11:51
That solves the first error (The type or namespace name 'Antlr4' could not be found)

But the others remain: http://pastebin.com/9npdNew1

Any idea on that?

**Comment by hfoffani** [comment] 2016-10-03 12:10
If you want to build the pddlnet.dll from source you'll need to install antlr4. I haven't tested the build procedure in Windows so I don't know how it would go.

Right now the dll is only published through Nuget and I thought that the common use-case would be to install the library from Visual Studio or Xamarin. That works as far as I know.

I could work on two other options:
1. Add a direct download from github and an example compiling it with the csc.exe.
2. Add an example using Visual Studio Code with a Nuget extension.

**Comment by marijngoedegebure** [comment] 2016-10-03 12:20
Either one of the two options you mention works for me. An example of installing the package through Nuget would be great.

But as I described in my first reply, I tried installing pddlnet through Nuget (in visual studio) but that resulted in this error: "Unable to resolve dependency 'pddlnet'. Source(s) used: 'nuget.org', 'Package source', 'Microsoft Visual Studio Offline Packages'." 

This might be something you might come across when testing out the Nuget example for Visual Studio.

**Comment by hfoffani** [comment] 2016-10-03 12:30
I'm sorry. I didn't know there were problems while installing the package from Nuget. Unless I'm able to reproduce it easily I'm afraid it would take me a lot time to fix it.

However I can publish a zip with just the dlls here in github so you can get a workaround. I'll add to it some .cs test and a Readme later.

**Comment by marijngoedegebure** [comment] 2016-10-03 12:37
Regarding the Nuget package installation, the only thing I noticed was that the nuget webpage of the dependency that is required results in a 404. (https://www.nuget.org/packages/pddlnet/). So that could be a start.

Whether or not you manage to find it, a zip with the dlls works fine for me.

**Comment by hfoffani** [comment] 2016-10-03 12:40
Thanks, yes. Definitely there's a misspelling. The package is at https://www.nuget.org/packages/pddlnet.dll/

**Comment by marijngoedegebure** [comment] 2016-10-03 12:41
Ye but that package has a dependency to https://www.nuget.org/packages/pddlnet/, which corresponds to the error thrown by nuget.

**Comment by hfoffani** [comment] 2016-10-03 12:44
Ah, now I see. It shouldn't have any dependencies as far I know.

**Comment by hfoffani** [comment] 2016-10-03 12:48
Bug #6

**Comment by hfoffani** [comment] 2016-10-03 12:49
Workaround #4

**Comment by hfoffani** [comment] 2016-10-04 12:47
There's a small zip with the compiled dlls. (pddlnet.dll and Antlr.Runtime.dll). It lacks any docs, so you want to look at the tests source code.

https://github.com/hfoffani/pddl-lib/releases/download/0.1.5/pddlnetdll.zip

Hope it works as a workaround.

**Comment by marijngoedegebure** [comment] 2016-10-04 13:02
Thanks a lot for the quick reply and understanding. I will test out the dlls in the coming days.

**Comment by marijngoedegebure** [comment] 2016-10-04 13:19
It works! Again, thanks a lot!

**Comment by hfoffani** [comment] 2016-10-04 15:58
Great! Sorry for the inconveniences. I'm closing this issue.

**Closed as completed by hfoffani** 2016-10-04 15:58 UTC
Labels: bug, question
